[cursor]
style = "Block"
unfocused_hollow = true

[env]
TERM = "xterm-256color"

[colors]
draw_bold_text_with_bright_colors = true

[font]
# draw_bold_text_with_bright_colors = true
size = 16

[font.bold]
# family = "Lekton Nerd Font Mono"
family = "JetBrainsMono Nerd Font"

[font.glyph_offset]
x = 0
y = 0

[font.italic]
# family = "Lekton Nerd Font Mono"
family = "JetBrainsMono Nerd Font"

[font.normal]
# family = "Lekton Nerd Font Mono"
family = "JetBrainsMono Nerd Font"

[font.offset]
x = 0
y = 0

[window]
# My New ones
# decorations = "full"
decorations = "buttonless"
dynamic_title = true
startup_mode = "Maximized"
# My old ones
# decorations = "buttonless"
# startup_mode = "Windowed"

[window.padding]
x = 4
y = 4

[general]
import = [
  "/Users/sonntaghimself/.config/alacritty/themes/themes/tokyonight_moon.toml",
]
# import = ["/Users/sonntaghimself/.config/alacritty/themes/melange_dark.toml"]
# import = ["/Users/sonntaghimself/.config/alacritty/themes/themes/gruvbox_dark.yaml"]
